//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tank1460.LevelImport.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tank1460.LevelImport.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Battle_City__J__15 {
            get {
                object obj = ResourceManager.GetObject("Battle City (J)-15", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Battle_City__J__6 {
            get {
                object obj = ResourceManager.GetObject("Battle City (J)-6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;Количество врагов по уровням:
        ///		:.BYTE $12, 2, 0, 0 ; 1
        ///		.BYTE 2, 4, 0, $E	; 2
        ///		.BYTE $E, 4, 0,	2	; 3
        ///		.BYTE $A, 5, 2,	3	; 4
        ///		.BYTE 5, 2, 8, 5	; 5
        ///		.BYTE 7, 2, 9, 2	; 6
        ///		.BYTE 3, 4, 6, 7	; 7
        ///		.BYTE 7, 2, 4, 7	; 8
        ///		.BYTE 6, 4, 7, 3	; 9
        ///		.BYTE $C, 2, 4,	2	; 10
        ///		.BYTE 5, 6, 4, 5	; 11
        ///		.BYTE 8, 6, 0, 6	; 12
        ///		.BYTE 8, 8, 0, 4	; 13
        ///		.BYTE $A, 4, 0,	6	; 14
        ///		.BYTE 2, 0, $A,	8	; 15
        ///		.BYTE $10, 0, 2, 2	; 16
        ///		.BYTE 2, 2, 8, 8	; 17
        ///		.BYTE 4, 2, 6, 8	; 18
        ///		.BYTE 4, 8, 4, 4	; 19
        ///		. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string level_bot_numbers {
            get {
                return ResourceManager.GetString("level bot numbers", resourceCulture);
            }
        }
    }
}
